#!/usr/bin/env python3

import argparse
import os
import sys

REPO_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..')
sys.path.insert(0, f'{REPO_PATH}/tower-lib')

from towerlib import buildhost, buildthinclient, utils

def parse_arguments():
    parser = argparse.ArgumentParser(description="""Generate TowerOS-ThinClient and TowerOS-Host images""")
    parser.add_argument(
        '-v', '--verbose',
        help="""Set log level to DEBUG.""",
        required=False,
        action='store_true',
        default=False
    )
    parser.add_argument(
        '--quiet',
        help="""Set log level to ERROR.""",
        required=False,
        action='store_true',
        default=False
    )
    subparser = parser.add_subparsers(
        dest='image_name', 
        required=True, 
        help="Use `build-tower-image {thinclient|host} --help` to get options list for each image."
    )

    subparser.add_parser(
        'thinclient',
        help="""Command used to generate thinclient image"""
    )

    host_parser = subparser.add_parser(
        'host',
        help="""Command used to generate host image."""
    )
    host_parser.add_argument(
        '-u', '--uncompressed',
        required=False,
        action='store_true',
        default=False,
    )
    args = parser.parse_args()
    return args

def main():
    args = parse_arguments()
    utils.clilogger.initialize(args.verbose, args.quiet)
    if args.image_name == 'host':
        buildhost.build_image(args.uncompressed)
    elif args.image_name == 'thinclient':
        buildthinclient.build_image()

if __name__ == '__main__':
    sys.exit(main())

