MACOS_NAME_TO_X11_CODE = {
    "Afghani": "af",
    "Albanian": "al",
    "Armenian": "am",
    "Arabic": "ara",
    "German (Austria)": "at",
    "English (Australian)": "au",
    "Azerbaijani": "az",
    "Bosnian": "ba",
    "Bengali": "bd",
    "Belgian": "be",
    "Bulgarian": "bg",
    "Portuguese (Brazil)": "br",
    "Braille": "brai",
    "Dzongkha": "bt",
    "Tswana": "bw",
    "Belarusian": "by",
    "French (Canada)": "ca",
    "French (Democratic Republic of the Congo)": "cd",
    "German (Switzerland)": "ch",
    "English (Cameroon)": "cm",
    "Chinese": "cn",
    "Czech": "cz",
    "German": "de",
    "Danish": "dk",
    "Berber (Algeria, Latin characters)": "dz",
    "Estonian": "ee",
    "Esperanto": "epo",
    "Spanish": "es",
    "Amharic": "et",
    "Finnish": "fi",
    "Faroese": "fo",
    "French": "fr",
    "English (UK)": "gb",
    "Georgian": "ge",
    "English (Ghana)": "gh",
    "French (Guinea)": "gn",
    "Greek": "gr",
    "Croatian": "hr",
    "Hungarian": "hu",
    "Indonesian (Jawi)": "id",
    "Irish": "ie",
    "Hebrew": "il",
    "Indian": "in",
    "Iraqi": "iq",
    "Persian": "ir",
    "Icelandic": "is",
    "Italian": "it",
    "Japanese": "jp",
    "Javanese": "jv",
    "Swahili (Kenya)": "ke",
    "Kyrgyz": "kg",
    "Khmer (Cambodia)": "kh",
    "Korean": "kr",
    "Kazakh": "kz",
    "Lao": "la",
    "Spanish (Latin American)": "latam",
    "Sinhala (phonetic)": "lk",
    "Lithuanian": "lt",
    "Latvian": "lv",
    "Arabic (Morocco)": "ma",
    "Maori": "mao",
    "Moldavian": "md",
    "Montenegrin": "me",
    "Macedonian": "mk",
    "Bambara": "ml",
    "Burmese": "mm",
    "Mongolian": "mn",
    "Maltese": "mt",
    "Dhivehi": "mv",
    "Malay (Jawi)": "my",
    "English (Nigeria)": "ng",
    "Dutch": "nl",
    "Norwegian": "no",
    "Nepali": "np",
    "Filipino": "ph",
    "Urdu (Pakistan)": "pk",
    "Polish": "pl",
    "Portuguese": "pt",
    "Romanian": "ro",
    "Serbian": "rs",
    "Russian": "ru",
    "Swedish": "se",
    "Slovenian": "si",
    "Slovak": "sk",
    "Wolof": "sn",
    "Arabic (Syria)": "sy",
    "French (Togo)": "tg",
    "Thai": "th",
    "Tajik": "tj",
    "Turkmen": "tm",
    "Turkish": "tr",
    "Taiwanese": "tw",
    "Swahili (Tanzania)": "tz",
    "Ukrainian": "ua",
    "English (US)": "us",
    "Uzbek": "uz",
    "Vietnamese": "vn",
    "English (South Africa)": "za"
}